# 2. Crie um Jupyter Notebook e use as bibliotecas criadas na Questão 1 para fazer o que se pede:

## 2.a Represente os dados a seguir:

In [1]:
from mylibs import stats as st, resample as rs, metrics as mt, linear_regression as lr, numpy as np
from sklearn import linear_model, metrics
from math import sqrt

dados = np.array([[1400,245.000], [1600,312.000], [1700,279.000], [1875,308.000], [1100,199.000],
            [1550,219.000], [2350,405.000], [2450,324.000], [1425,319.000], [1700,255.000]])

X = dados[:, 0]
y = dados[:, 1]

X,y

(array([1400., 1600., 1700., 1875., 1100., 1550., 2350., 2450., 1425.,
        1700.]),
 array([245., 312., 279., 308., 199., 219., 405., 324., 319., 255.]))

## 2.b Calcule média, desvio padrão e variância de X

In [2]:
print(st.mean(X))
print(st.var(X))
print(st.stddev(X))

1715.0
157150.0
396.42149285829595


## 2.c Divida os dados X, y para 70% de treino e 30% de teste. O resultado deve estar nas variáveis: X_train, y_train, X_test, y_test.

In [3]:
idx_train, idx_teste = rs.split_train_test(len(X), 0.7, 0)

idx_train, idx_teste

([2, 8, 4, 9, 1, 6, 7], [3, 0, 5])

In [4]:
X_train = X[idx_train]
y_train = y[idx_train]
X_test = X[idx_teste]
y_test = y[idx_teste]

## 2.d Crie um modelo de (1) SimpleLinearRegression (sua implementação) e outro modelo usando (2) LinearRegression do Scikit Learn.

In [5]:
modelo1 = lr.SimpleLinearRegression()
modelo2 = linear_model.LinearRegression()

## 2.e Treine os modelos com os dados de treino (X_train, y_train)

In [6]:
modelo1.fit(X_train, y_train)
b0_1 = modelo1.b0
b1_1 = modelo1.b1

b0_1, b1_1

(122.4675225626033, 0.10026185331130034)

In [7]:
X_train2 = [[i] for i in X_train]
modelo2.fit(X_train2, y_train)
b1_2 = modelo2.coef_
b0_2 = modelo2.intercept_

b0_2, b1_2[0]

(122.46752256260325, 0.10026185331130039)

# 2.f Faça as predições para os modelos usando os dados de teste (X_test)]

In [8]:
y_pred = modelo1.predict(X_test)

X_test, y_pred

(array([1875., 1400., 1550.]),
 array([310.45849752, 262.8341172 , 277.8733952 ]))

In [9]:
X_test2 = [[i] for i in X_test]
y_pred2 = modelo2.predict(X_test2)

X_test2, y_pred2

([[1875.0], [1400.0], [1550.0]],
 array([310.45849752, 262.8341172 , 277.8733952 ]))

## 2.g Calcule as métricas MSE, RMSE e MAE para avaliar os modelos criados comparando os rótulos dos dados de teste (y_test) com os dados preditos (y_pred).

In [10]:
mse = mt.mse(y_test, y_pred)
rmse = mt.rmse(y_test, y_pred)
mae = mt.mae(y_test, y_pred)

mse, mae, rmse

(1263.3922027033184, 26.388669971611364, 35.54422882414694)

In [13]:
mse2 = metrics.mean_squared_error(y_test, y_pred2)
rmse2 = sqrt(metrics.mean_squared_error(y_test, y_pred2))
mae2 = metrics.mean_absolute_error(y_test, y_pred2)

mse2, mae2, rmse2

(1263.3922027033184, 26.388669971611364, 35.54422882414694)